# Razorops configuration file for a Java application

version: 1

# Define the Docker image to use
image:
  name: openjdk:11

# Define the stages of the pipeline
stages:
  - build
  - test
  - deploy

# Define the jobs for each stage
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Build the application
          command: |
            ./gradlew build

  test:
    steps:
      - run:
          name: Run unit tests
          command: |
            ./gradlew test

  deploy:
    steps:
      - deploy:
          name: Deploy to production
          environment: production
          command: |
            ./gradlew deploy
